### ISSUE TITLE
Add MedleyDB 2.0 tracks

### ISSUE THREAD

**Issue by faroit** [sigsep/sigsep-mus-mdbconvert#1]
MedleyDB 2.0 quite some time ago. We should add the tracks, ideally by rerunning this script. 

@rabitt is there any breaking changes regarding the taxonomy or stem gains regarding automatic mixing?

**Comment by rabitt** [comment]
@faroit (sorry didn't see this until just now!) No breaking changes, but the majority of the tracks in MedleyDB 2.0 have bleed, so only a handful of them will be useful for you for source separation.

**Comment by faroit** [comment]
okay then. even a handful might be worth it ;-)
